### ISSUE TITLE
cant get it to run 

### ISSUE THREAD

**Issue by philip223** [I2rys/NRSBackdoor#1]
hey I cant get the program to run, I followed all the instructions and also updated node and npm. when I try to run it on visual studios it gives me this " crbug/1173575, non-JS module files deprecated" and on the browser it just says this site cant be reached and the error is "ERR_CONNECTION_REFUSED" if I run it as an exe file it just opens and closes cmd 

thank you in advance

**Comment by I2rys** [comment]
Hello @philip223,
I tested NRSBackdoor v1.0.0 as well as NRSBackdoor v1.0.1 and it's completely working. Can you please send the NRSBackdoor code that you setup, or the whole folder so I can look for the problem faster & fix it.

Questions:
What NPM Packages did you installed as well as the versions?
Which software did you use Visual Studio/Visual Studio Code?
What NodeJS & NPM version are you using?

If you want to send it privately, please DM me on discord. SucY#3048

**Comment by philip223** [comment]
Hey thank you for your reply. 

**Answers**

1. these are the package.json file  
   `{
  "dependencies": {
    "discord.js": "^13.1.0",
    "express": "^4.17.1",
    "express-param": "^1.6.1",
    "localtunnel": "^2.0.1",
    "os": "^0.1.2",
    "simple-exec": "^2.1.0"
  }
}
`

2. Im using Visual Studio. 

3. and my Node version is 16.8. and NPM version is 7.21.0

Ive send you a friend request over discord, again thank you very much.
