### ISSUE TITLE
Browse dirs

### ISSUE THREAD

**Issue by Crims-on** [I2rys/NRSBackdoor#2]
Is there any way to browse through directories? I've tried cmd?exec=cd+..  and cmd?exec=cd .. , but they aren't working

btw I found a problem in your code making it a problem to send webhook. Webhook info should be like this:

```
const data = {
    id: 'webhook_id',
    token: 'webhook_token'
}
//Variables
const Webhook = new Discord.WebhookClient(data)
```

**Comment by I2rys** [comment]
> Is there any way to browse through directories? I've tried cmd?exec=cd+.. and cmd?exec=cd .. , but they aren't working
> 
> btw I found a problem in your code making it a problem to send webhook. Webhook info should be like this:
> 
> ```
> const data = {
>     id: 'webhook_id',
>     token: 'webhook_token'
> }
> //Variables
> const Webhook = new Discord.WebhookClient(data)
> ```

Hello @Crims-on,
I'm not sure which directory you are trying to browse but you can use **os** and **fs** library then make a code to do a recursive reading in the specified directory or use this library instead **recursive-readdir-async**.
